#!/usr/bin/env python3
"""Per-simulation runner for TAMULauncher.

Each TAMULauncher command line calls this script with a single job_id.
It runs the corresponding Sugarscape simulation, measures wall-clock time
and peak RSS, and writes a small timing JSON to timing_sim_<job_id>.json in the root directory.

Usage (generated by generate_commands.py):
    python run_sim.py --project-dir /path/to/project --job-id 42
"""

import argparse
import csv
import datetime
import json
import os
import subprocess
import sys
import time


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run a single Sugarscape simulation (TAMULauncher worker)"
    )
    parser.add_argument(
        "--project-dir", required=True,
        help="Root directory containing SugarCluster/ and sugarscape/"
    )
    parser.add_argument(
        "--job-id", type=int, required=True,
        help="1-indexed job ID from jobs.csv"
    )
    args = parser.parse_args()

    cluster_dir = os.path.join(args.project_dir, "SugarCluster")
    sugarscape_dir = os.path.join(args.project_dir, "sugarscape")
    manifest = os.path.join(cluster_dir, "jobs.csv")
    sugarscape_py = os.path.join(sugarscape_dir, "sugarscape.py")
    python_bin = sys.executable  # inherit the interpreter that launched run_sim.py


    # Timing output path (one JSON per sim, stored in root directory)
    timing_path = os.path.join(cluster_dir, f"timing_sim_{args.job_id}.json")

    param_names = [
        "diseaseTransmissionChance",
        "diseaseTagStringLength",
        "agentImmuneSystemLength",
        "diseaseSugarMetabolismPenalty",
    ]

    # --- Load manifest row ---
    if not os.path.exists(manifest):
        msg = f"ERROR: Manifest not found: {manifest}"
        print(msg, file=sys.stderr)
        _write_timing_early(timing_path, args.job_id, "MANIFEST_MISSING")
        return 1

    with open(manifest, newline="") as f:
        reader = csv.DictReader(f)
        jobs = list(reader)

    total_jobs = len(jobs)
    if args.job_id < 1 or args.job_id > total_jobs:
        msg = f"ERROR: job_id {args.job_id} out of range (1–{total_jobs})"
        print(msg, file=sys.stderr)
        _write_timing_early(timing_path, args.job_id, "ID_OUT_OF_RANGE")
        return 1

    row = jobs[args.job_id - 1]
    config_rel = row["config_path"]
    config_path = os.path.join(cluster_dir, config_rel)
    label = f"[{args.job_id}/{total_jobs}] {row['run_type']} {row['framework']}"

    if not os.path.exists(config_path):
        print(f"{label} SKIPPED — config not found: {config_path}", file=sys.stderr)
        _write_timing(
            timing_path, args.job_id, row, param_names,
            duration=0.0, peak_memory_mb=0.0, status="CONFIG_MISSING"
        )
        return 1

    if not os.path.exists(sugarscape_py):
        print(f"ERROR: sugarscape.py not found: {sugarscape_py}", file=sys.stderr)
        _write_timing(
            timing_path, args.job_id, row, param_names,
            duration=0.0, peak_memory_mb=0.0, status="SUGARSCAPE_MISSING"
        )
        return 1

    print(f"{label} running {config_rel}", flush=True)

    # --- Run simulation ---
    # Sugarscape writes its logfile (bare name) relative to cwd.
    # cwd is not overridden here — output goes to whatever directory
    # TAMULauncher ran this script from (typically SugarCluster/).
    sim_start = time.perf_counter()
    start_wall = datetime.datetime.now(datetime.timezone.utc)
    p = subprocess.Popen(
        [python_bin, sugarscape_py, "--conf", config_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )

    peak_rss_kb = 0
    while True:
        ret = p.poll()
        try:
            with open(f"/proc/{p.pid}/status") as pf:
                for line in pf:
                    if line.startswith("VmRSS:"):
                        rss = int(line.split()[1])
                        if rss > peak_rss_kb:
                            peak_rss_kb = rss
                        break
        except Exception:
            pass
        if ret is not None:
            break
        time.sleep(0.05)

    stdout, stderr = p.communicate()
    sim_end = time.perf_counter()
    end_wall = datetime.datetime.now(datetime.timezone.utc)
    duration = sim_end - sim_start
    peak_memory_mb = round(peak_rss_kb / 1024.0, 2)

    if p.returncode != 0:
        status = f"EXIT_{p.returncode}"
        print(
            f"{label} FAILED ({status}) in {duration:.1f}s "
            f"(Peak Mem: {peak_memory_mb:.2f}MB)\n"
            f"  stdout: {stdout.strip()[:200]}\n"
            f"  stderr: {stderr.strip()[:200]}",
            file=sys.stderr,
        )
    else:
        status = "OK"
        print(f"{label} OK ({duration:.1f}s, Peak Mem: {peak_memory_mb:.2f}MB)", flush=True)

    _write_timing(
        timing_path, args.job_id, row, param_names,
        duration, peak_memory_mb, status,
        start_wall, end_wall,
    )

    return 0 if status == "OK" else 1


def _write_timing_early(path: str, job_id: int, status: str) -> None:
    """Write a minimal timing stub when run_sim.py fails before loading the manifest."""
    record = {"job_id": job_id, "status": status, "duration_seconds": 0.0}
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            json.dump(record, f)
    except Exception as e:
        print(f"WARNING: Could not write timing stub to {path}: {e}", file=sys.stderr)


def _write_timing(
    path: str,
    job_id: int,
    row: dict,
    param_names: list[str],
    duration: float,
    peak_memory_mb: float,
    status: str,
    start_time: "datetime.datetime | None" = None,
    end_time: "datetime.datetime | None" = None,
) -> None:
    record = {
        "job_id": job_id,
        "run_type": row.get("run_type", ""),
        "framework": row.get("framework", ""),
        **{p: row.get(p, "") for p in param_names},
        "start_time": start_time.isoformat() if start_time else None,
        "end_time": end_time.isoformat() if end_time else None,
        "duration_seconds": round(duration, 1),
        "peak_memory_mb": peak_memory_mb,
        "status": status,
    }
    try:
        with open(path, "w") as f:
            json.dump(record, f)
    except Exception as e:
        print(f"WARNING: Could not write timing to {path}: {e}", file=sys.stderr)


if __name__ == "__main__":
    sys.exit(main())
