[simulation]
timesteps = 1000
seed = 12345
headless_mode = true
logfile_format = "json"

[sweep.models]
frameworks = [
  "none",
  "altruist",
  "bentham",
  "egoist",
  "negativeBentham",
  "asimov",
  "temperance",
  "temperancePECS"
]

[disease]
startingDiseases = 25
startingDiseasesPerAgent = [10, 10]

[disease.sweep]
diseaseTransmissionChance = [0.3, 0.6, 1.0]
diseaseTagStringLength = [5, 13, 21]
agentImmuneSystemLength = [10, 35, 60]
diseaseSugarMetabolismPenalty = [0, 0.1, 0.25, 0.5, 1, 2, 3]

[baseline]
enabled = true
